name: 'GitHub Actions '

on:
  workflow_dispatch:
  schedule:
   - cron: '0 14 * * *'
jobs:
  ddy:
    runs-on: ubuntu-latest
    steps:
      - name: Set time zone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: 'Working'
        # timeout-minutes: 360
        run: |
          wget -O ip.txt  https://raw.githubusercontent.com/ppxko/find-x/refs/heads/main/fancy/real_ip.txt
          chmod +x ./meta_iptest.sh
          bash ./meta_iptest.sh
      - name: Commit files          
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "⌚️$(date +%Y%m%d%H%M%S)" -a
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m 'Add real_ip.txt'
            git push
          fi
